# Generated by Django 3.1.8 on 2021-08-06 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('number_of_products', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
    ]
