# Generated by Django 3.1.8 on 2021-08-06 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='number_of_products',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
